import {spawn} from 'node:child_process';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const directory=resolve(`.browser-preview/redesign-${Date.now()}`);
mkdirSync(directory,{recursive:true});
mkdirSync('docs/screenshots/redesign',{recursive:true});
const browser=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=9224',`--user-data-dir=${directory}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
const delay=ms=>new Promise(done=>setTimeout(done,ms));
let socket;
try {
  for(let i=0;i<40;i++){try{if((await fetch('http://localhost:9224/json/version')).ok)break;}catch{}await delay(250);}
  const target=await(await fetch('http://localhost:9224/json/new?about:blank',{method:'PUT'})).json();
  socket=new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((done,reject)=>{socket.addEventListener('open',done,{once:true});socket.addEventListener('error',reject,{once:true});});
  const pending=new Map();let serial=0;const issues=[];
  socket.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id){const task=pending.get(m.id);pending.delete(m.id);if(m.error)task?.reject(m.error);else task?.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')issues.push(m.params.exceptionDetails.exception?.description??m.params.exceptionDetails.text);if(m.method==='Runtime.consoleAPICalled'&&m.params.type==='error')issues.push(m.params.args.map(a=>a.value??a.description).join(' '));});
  const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
  await send('Runtime.enable');await send('Page.enable');
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw Error(result.exceptionDetails.exception?.description??result.exceptionDetails.text);return result.result.value;};
  const navigate=async path=>{await send('Page.navigate',{url:`http://localhost:3100${path}`});await delay(400);for(let i=0;i<80;i++){if(await evaluate("document.readyState==='complete' && !!document.querySelector('h1')"))break;await delay(100);}await delay(250);};
  const viewport=async(width,height=1000)=>{await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<600});await delay(150);};
  const screenshot=async name=>{const result=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(`docs/screenshots/redesign/${name}.png`,Buffer.from(result.data,'base64'));};
  const click=async(text,scope='main')=>{await evaluate(`(()=>{const root=document.querySelector(${JSON.stringify(scope)});const item=[...root.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(text)});if(!item)throw Error('Missing button '+${JSON.stringify(text)});item.click();})()`);await delay(200);};
  const schedule=async()=>{await evaluate("document.querySelector('.planner-title-row button').click()");await delay(200);};
  const fill=async(label,value,scope='dialog[open]')=>{await evaluate(`(()=>{const root=document.querySelector(${JSON.stringify(scope)});const label=[...root.querySelectorAll('label')].find(l=>l.textContent.trim()===${JSON.stringify(label)});if(!label)throw Error('Missing label '+${JSON.stringify(label)});const input=document.getElementById(label.htmlFor);const proto=input.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:input.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(input,${JSON.stringify(value)});input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));})()`);await delay(120);};
  const read=()=>evaluate("JSON.parse(localStorage.getItem('studyflow.workspace.v1'))");
  await send('Network.setCookie',{name:'NEXT_LOCALE',value:'en',domain:'localhost',path:'/'});
  await viewport(1440);await navigate('/dashboard');await evaluate("localStorage.removeItem('studyflow.workspace.v1');localStorage.setItem('theme-mode','light')");
  if(process.argv.includes('--hero')) {await (await import('./dashboard-hero-audit.mjs')).default({evaluate,navigate,viewport,screenshot,send});assert.deepEqual(issues,[],'browser errors');} else if(process.argv.includes('--polish') || process.argv.includes('--baseline')) {await (await import('./polish-audit.mjs')).default({evaluate,navigate,viewport,screenshot,send},process.argv.includes('--baseline'),process.argv.includes('--interactions'));assert.deepEqual(issues,[],'browser errors');} else {
  const routes=process.argv.includes('--planner') ? ['/calendar'] : ['/dashboard','/subjects','/subjects/aws','/study','/study/history','/calendar','/analytics','/resources','/settings','/onboarding','/onboarding/context','/onboarding/subject','/onboarding/topics','/onboarding/goal','/login','/register','/forgot-password','/reset-password','/admin','/admin/users','/admin/users/learner-1','/admin/analytics','/admin/storage','/admin/settings','/terms','/privacy','/error-404','/error-500'];
  const report=[];
  for(const theme of ['light','dark']){
    await evaluate(`localStorage.setItem('theme-mode',${JSON.stringify(theme)})`);
    for(const width of (process.argv.includes('--planner') ? [1440,1024,768,360] : [1440,360])){
      await viewport(width);
      for(const route of routes){await navigate(route);const result=await evaluate(`({heading:document.querySelector('h1')?.textContent,overflow:document.documentElement.scrollWidth,theme:document.documentElement.classList.contains('dark'),errors:document.body.innerText.includes('MISSING_MESSAGE')})`);report.push({route,theme,width,...result});assert.ok(result.heading,route);assert.ok(!result.errors,route);assert.ok(result.overflow<=width,`${route} ${theme} ${width} overflow ${result.overflow}`);await screenshot(`${route.slice(1).replaceAll('/','-')}-${theme}-${width}`);console.log(`PASS ${theme} ${width} ${route}`);}
    }
  }
  if(process.argv.includes('--planner')) {
    await viewport(1440);await evaluate("localStorage.setItem('theme-mode','light')");await navigate('/calendar');
    const layout=await evaluate("(()=>{const r=document.querySelector('.planner-timetable').getBoundingClientRect();return {width:r.width,x:r.x,bottom:r.bottom,height:innerHeight,agenda:!!document.querySelector('.sf-planner-agenda')}})()");
    assert.ok(layout.width>1100);assert.ok(Math.abs(layout.bottom-layout.height)<3);assert.ok(!layout.agenda);
    await click('Month','.planner-view-switch');await screenshot('planner-month');await click('Week','.planner-view-switch');
    const range=await evaluate("document.querySelector('.planner-range').textContent");await evaluate("document.querySelector('button[aria-label=Next]').click()");await delay(200);assert.notEqual(await evaluate("document.querySelector('.planner-range').textContent"),range);await click('Today','.planner-navigation');
    await schedule();await fill('Title (Class, Exam, Break…)','Short planner verification');const date=new Date().toISOString().slice(0,10);await fill('Start (Asia/Colombo)',`${date}T15:10`);await fill('End (Asia/Colombo)',`${date}T15:20`);await click('Save','dialog[open]');
    assert.ok((await read()).blocks.some(b=>b.title==='Short planner verification'));
    await evaluate("[...document.querySelectorAll('.planner-event')].find(b=>b.textContent.includes('Short planner verification')).click()");await delay(200);await screenshot('calendar-details');await click('Duplicate','dialog[open]');await fill('Title (Class, Exam, Break…)','Duplicate planner verification');await fill('Start (Asia/Colombo)',`${date}T15:30`);await fill('End (Asia/Colombo)',`${date}T15:45`);await click('Save','dialog[open]');assert.ok((await read()).blocks.some(b=>b.title==='Duplicate planner verification'));
    await screenshot('planner-event-layout');
    const eventBounds=await evaluate("[...document.querySelectorAll('.planner-event')].filter(e=>e.textContent.includes('Short planner verification')).map(e=>{const a=e.getBoundingClientRect(),b=e.querySelector('.planner-event-inner').getBoundingClientRect();return {outerHeight:a.height,innerHeight:b.height,outerWidth:a.width,innerWidth:b.width,bg:getComputedStyle(e).backgroundColor}})");assert.ok(eventBounds.every(e=>e.innerWidth<=e.outerWidth && e.innerHeight<=e.outerHeight && e.bg!=='rgba(0, 0, 0, 0)'));console.log('PASS planner viewport, view controls, navigation, scheduling, event details, duplication and event containment');
    const beforeDrag=(await read()).blocks.find(b=>b.title==='Short planner verification');
    await evaluate("(()=>{const event=[...document.querySelectorAll('.planner-event')].find(e=>e.textContent.includes('Short planner verification'));let p=event.parentElement;while(p){if(p.scrollHeight>p.clientHeight && /auto|scroll/.test(getComputedStyle(p).overflowY)){p.scrollTop+=event.getBoundingClientRect().top-p.getBoundingClientRect().top-100;break;}p=p.parentElement;}})()");await delay(250);
    const position=await evaluate("(()=>{const r=[...document.querySelectorAll('.planner-event')].find(e=>e.textContent.includes('Short planner verification')).getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()");
    await send('Input.dispatchMouseEvent',{type:'mouseMoved',...position});await send('Input.dispatchMouseEvent',{type:'mousePressed',...position,button:'left',clickCount:1});await delay(300);for(let step=1;step<=5;step++){await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:position.x,y:position.y+76*step/5,button:'left',buttons:1});await delay(100);}await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:position.x,y:position.y+76,button:'left',clickCount:1});await delay(500);assert.notEqual((await read()).blocks.find(b=>b.id===beforeDrag.id).startsAt,beforeDrag.startsAt);console.log('PASS pointer drag persists the new time');
  } else {
  await viewport(1440);await evaluate("localStorage.setItem('theme-mode','light')");await navigate('/subjects');await click('Add Subject');await fill('Title','Redesign verification');await click('Save','dialog[open]');let data=await read();const subject=data.subjects.find(s=>s.title==='Redesign verification');assert.ok(subject);
  await navigate(`/subjects/${subject.id}`);await click('Topics');await fill('New topic','First step','main');await click('Add Topic');await evaluate("document.querySelector('main input[type=checkbox]').click()");await delay(200);assert.equal((await read()).topics.find(t=>t.subjectId===subject.id).status,'completed');
  await navigate('/dashboard');await click('Start Studying','.sf-topbar');await fill('Subject',subject.id);await fill('Focus goal (optional)','Practice five questions');await click('Start','dialog[open]');assert.equal((await read()).timer.focusGoal,'Practice five questions');await navigate('/subjects');assert.ok(await evaluate("!!document.querySelector('.sf-timer-dock')"));await evaluate("document.querySelector('.sf-timer-dock button').click()");await delay(200);assert.ok((await read()).timer.pausedAt);await navigate('/study');await screenshot('focus-paused');await click('Resume');assert.ok(!(await read()).timer.pausedAt);await click('Finish');await click('Save session','dialog[open]');assert.equal((await read()).timer,null);
  await navigate('/calendar');await schedule();await fill('Subject',subject.id);await fill('Title (Class, Exam, Break…)','Verification planner block');const date=new Date().toISOString().slice(0,10);await fill('Start (Asia/Colombo)',`${date}T21:00`);await fill('End (Asia/Colombo)',`${date}T22:00`);await click('Save','dialog[open]');data=await read();assert.ok(data.blocks.find(b=>b.title==='Verification planner block'));
  await evaluate("[...document.querySelectorAll('.planner-event')].find(b=>b.textContent.includes('Verification planner block')).click()");await delay(250);await screenshot('calendar-details');await click('Duplicate','dialog[open]');await fill('Title (Class, Exam, Break…)','Duplicated block');await fill('Start (Asia/Colombo)',`${date}T23:00`);await fill('End (Asia/Colombo)',`${date}T23:30`);await click('Save','dialog[open]');assert.ok((await read()).blocks.find(b=>b.title==='Duplicated block'));
  await navigate('/admin/users');await fill('Status','inactive','main');assert.ok(await evaluate("[...document.querySelectorAll('tbody tr')].every(row=>row.innerText.includes('Inactive'))"));
  }
  await send('Network.setCookie',{name:'NEXT_LOCALE',value:'ar',domain:'localhost',path:'/'});for(const width of [1440,360]){await viewport(width);for(const route of ['/dashboard','/calendar','/subjects','/admin','/login']){await navigate(route);assert.equal(await evaluate('document.documentElement.dir'),'rtl');assert.ok(await evaluate(`document.documentElement.scrollWidth<=${width}`));await screenshot(`rtl-${route.slice(1)}-${width}`);}}
  writeFileSync('docs/screenshots/redesign/report.json',JSON.stringify({routes:report,issues},null,2));assert.deepEqual(issues,[],'browser errors');console.log('PASS interaction, localization, theme and responsive checks');
  }
}finally{socket?.close();browser.kill();}
