import type * as s from "@/lib/db/schema";
import type { Subject, Topic, Resource, StudySession, ScheduleBlock, ActiveTimer, Notification } from "@/types";

export const subjectRecord = (r: typeof s.subjects.$inferSelect): Subject => ({ id: r.id, userId: r.userId, title: r.title, description: r.description, color: r.displayColor as Subject["color"], targetDate: r.targetDate ?? undefined, status: r.status, createdAt: r.createdAt.toISOString(), updatedAt: r.updatedAt.toISOString() });
export const topicRecord = (r: typeof s.topics.$inferSelect): Topic => ({ id: r.id, subjectId: r.subjectId, title: r.title, description: r.description ?? undefined, status: r.status === "not_started" ? "notStarted" : r.status === "in_progress" ? "inProgress" : "completed", targetDate: r.targetDate ?? undefined, sortOrder: r.sortOrder, archived: r.archived, completedAt: r.completedAt?.toISOString(), createdAt: r.createdAt.toISOString(), updatedAt: r.updatedAt.toISOString() });
// Signed URLs and storage keys are deliberately excluded from mutation responses.
export const resourceRecord = (r: typeof s.resources.$inferSelect): Resource => ({ id: r.id, userId: r.userId, subjectId: r.subjectId, topicId: r.topicId ?? undefined, type: r.type, title: r.title, url: r.url ?? undefined, textContent: r.textContent ?? undefined, mimeType: r.mimeType ?? undefined, sizeBytes: r.sizeBytes, createdAt: r.createdAt.toISOString() });
export const sessionRecord = (r: typeof s.studySessions.$inferSelect): StudySession => ({ id: r.id, userId: r.userId, subjectId: r.subjectId, topicId: r.topicId ?? undefined, startedAt: r.startedAt.toISOString(), endedAt: r.endedAt.toISOString(), durationSeconds: r.durationSeconds, source: r.source, status: r.status, note: r.note ?? undefined, createdAt: r.createdAt.toISOString() });
export const blockRecord = (r: typeof s.scheduleBlocks.$inferSelect, exceptions: ScheduleBlock["exceptions"]): ScheduleBlock => ({ id: r.id, userId: r.userId, subjectId: r.subjectId ?? undefined, topicId: r.topicId ?? undefined, title: r.title, startsAt: r.startsAt.toISOString(), endsAt: r.endsAt.toISOString(), repeat: r.recurrenceRule ? "weekly" : "once", weekdays: r.recurrenceRule?.weekdays ?? [], recurrenceUntil: r.recurrenceRule?.until, timezone: r.timezone, note: r.note ?? undefined, color: r.displayColor as ScheduleBlock["color"], createdAt: r.createdAt.toISOString(), updatedAt: r.updatedAt.toISOString(), exceptions });
export const timerRecord = (r?: typeof s.activeTimers.$inferSelect): ActiveTimer | null => r ? ({ subjectId: r.subjectId, topicId: r.topicId ?? undefined, startedAt: r.startedAt.toISOString(), pausedAt: r.pausedAt?.toISOString(), pausedTotalSeconds: r.pausedTotalSeconds, confirmedUntilSeconds: r.confirmedUntilSeconds, focusGoal: r.focusGoal ?? undefined }) : null;
export const notificationRecord = (r: typeof s.notifications.$inferSelect): Notification => ({ id: r.id, userId: r.userId, type: r.type as Notification["type"], title: r.title, body: r.body, scheduledFor: r.scheduledFor.toISOString(), readAt: r.readAt?.toISOString(), createdAt: r.createdAt.toISOString() });
